video:
  size:
    width: 2560
    height: 1440
  rtsp_urls:
    - "rtsp://admin:Daxhuz-kitnor-cekvi5@192.168.3.49/Preview_01_main"
    - "rtsp://admin:Daxhuz-kitnor-cekvi5@192.168.3.47/Preview_01_main"
    - "rtsp://admin:Daxhuz-kitnor-cekvi5@192.168.3.52/Preview_01_main"
  active_url: 2

model:
  path: "models/yolov8m-pose.pt"
